# Generated by Django 5.2.5 on 2025-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(default='To be announced', max_length=100),
        ),
    ]
