# Generated by Django 5.2.5 on 2025-09-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_telebirraccount_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='TelebirrAccount',
        ),
    ]
