# Generated by Django 4.2.11 on 2025-09-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_add_chapa_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.DeleteModel(
            name='ChapaTransaction',
        ),
    ]
