# Generated by Django 5.2.5 on 2025-10-01 12:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_course_duration_weeks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('completion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('WITHDRAWN', 'Withdrawn')], default='IN_PROGRESS', max_length=20)),
                ('progress_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('certificate_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='students.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status'], name='students_co_student_b24e91_idx'), models.Index(fields=['course', 'status'], name='students_co_course__12f2a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_completion')],
            },
        ),
    ]
