# Generated by Django 5.2.5 on 2025-10-21 09:08

import django.db.models.deletion
import students.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_coursecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('material_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('VIDEO', 'Video File'), ('PDF', 'PDF Document'), ('URL', 'External URL')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=students.models.course_material_upload_path)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='students.course')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['course', 'material_type'], name='students_co_course__966553_idx'), models.Index(fields=['course', 'is_visible'], name='students_co_course__01742e_idx')],
            },
        ),
    ]
