# Generated by Django 5.2.5 on 2025-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('VIDEO', 'Video File'), ('PDF', 'PDF Document'), ('URL', 'External URL'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
