# Generated by Django 5.2.5 on 2025-10-27 15:05

import django.db.models.deletion
import students.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_coursematerial_is_important_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterialFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=students.models.course_material_file_upload_path)),
                ('file_type', models.CharField(choices=[('VIDEO', 'Video File'), ('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('OTHER', 'Other')], default='DOCUMENT', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.coursematerial')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['material', 'file_type'], name='students_co_materia_de6d4b_idx'), models.Index(fields=['material', 'is_visible'], name='students_co_materia_226d48_idx')],
            },
        ),
    ]
