# Generated by Django 5.2.5 on 2025-10-27 16:53

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_coursematerialfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF)', null=True, upload_to=students.models.student_profile_picture_upload_path),
        ),
    ]
