# Generated by Django 5.2.5 on 2025-11-25 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='students.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to='students.student')),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['student', 'material'], name='students_ma_student_cdc6f4_idx'), models.Index(fields=['material', 'student'], name='students_ma_materia_697668_idx')],
                'unique_together': {('student', 'material')},
            },
        ),
    ]
