# Generated by Django 5.2.5 on 2025-11-25 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_materialviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEngagementSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_sessions', to='students.course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_sessions', to='students.coursematerial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_sessions', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'material'], name='students_ma_student_eb8780_idx'), models.Index(fields=['course', 'material'], name='students_ma_course__a522fd_idx')],
            },
        ),
    ]
