# Generated by Django 5.2.5 on 2026-01-20 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_materialengagementsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this course (used in teacher dashboard).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='students.teacher'),
        ),
    ]
