# Generated by Django 5.2.5 on 2026-01-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_teacher_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved courses are visible to students.'),
        ),
    ]
