# Generated by Django 5.2.5 on 2026-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_course_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Admin must approve before teacher gets full access.', max_length=20),
        ),
    ]
