# Generated by Django 5.2.5 on 2026-01-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='kind',
            field=models.CharField(choices=[('LESSON', 'Lesson'), ('ASSIGNMENT', 'Assignment')], default='LESSON', max_length=20),
        ),
    ]
