# Generated by Django 5.2.5 on 2026-01-26 18:11

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_coursematerial_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF)', null=True, upload_to=students.models.teacher_profile_picture_upload_path),
        ),
    ]
