# Generated by Django 5.2.5 on 2026-01-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_teacher_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='status',
        ),
    ]
