# Generated by Django 5.2.5 on 2026-02-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_remove_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Unique staff identifier (only teachers have this; students do not).', max_length=20, null=True, unique=True),
        ),
    ]
