# Generated by Django 5.2.5 on 2026-02-18 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_exam_system'),
        ('students', '0026_add_staff_invitation_assignment_exam'),
    ]

    operations = [
    ]
