# Generated by Django 5.2.12 on 2026-04-27 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_merge_20260218_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_file',
            field=models.FileField(blank=True, help_text='Main course document/PDF file', null=True, upload_to='course_materials/main_files/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='num_questions',
            field=models.PositiveIntegerField(default=10, help_text='Number of questions to generate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
